### ISSUE TITLE
TODO [24.07.14]

### ISSUE THREAD

**Issue by lucy0701** [lucy0701/Simpang_Client#26]
- [ ] image loading - 1
- [x] 컨텐츠 만들기 - 1
- [x] 컨텐츠 생성 글자 수 제한 변경 
- [ ] tag 설정
- [x] SEO (구글/네이버) - 2
- [ ] Open Graph - 2
- [ ] 광고 배너 추가 - 3
- [x] README 업데이트
